# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libimage-exiftool-perl
  - pip install codecov

install:
  - pip install -r requirements.txt

before_script:
  - pip install -r test_requirements.txt
  - pip install coveralls

script:
  - coverage run --source pic2map setup.py test

after_success:
  - coveralls
  - codecov
