# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libimage-exiftool-perl

install:
  - pip install -r requirements.txt -r test_requirements.txt codecov coveralls

script:
  - coverage run --source pic2map setup.py test

after_success:
  - codecov
  - coveralls

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/b62b577aaf57e656eaaa
